class Autogenerated {
  Message? message;

  Autogenerated({this.message});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    message =
        json['message'] != null ? new Message.fromJson(json['message']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.message != null) {
      data['message'] = this.message!.toJson();
    }
    return data;
  }
}

class Message {
  int? status;
  String? message;
  String? token;
  User? user;

  Message({this.status, this.message, this.token, this.user});

  Message.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message'];
    token = json['token'];
    user = json['user'] != null ? new User.fromJson(json['user']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['message'] = this.message;
    data['token'] = this.token;
    if (this.user != null) {
      data['user'] = this.user!.toJson();
    }
    return data;
  }
}

class User {
  int? id;
  String? role;
  String? userMail;
  String? phoneNumber;
  String? companyName;
  String? simSlot;

  User(
      {this.id,
      this.role,
      this.userMail,
      this.phoneNumber,
      this.companyName,
      this.simSlot});

  User.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    role = json['role'];
    userMail = json['email'];
    phoneNumber = json['phone'];
    companyName = json['company_name'];
    simSlot = json['sim_slot'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['role'] = this.role;
    data['email'] = this.userMail;
    data['phone'] = this.phoneNumber;
    data['company_name'] = this.companyName;
    data['sim_slot'] = this.simSlot;
    return data;
  }
}
